ServerRoot "{{ROOT}}/bin/httpd-2.4.66-251206-Win64-VS17/Apache24"


Listen 80
Listen 443


<IfModule mod_ssl.c>
    SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
    SSLCipherSuite HIGH:!aNULL
</IfModule>


ServerName localhost:8080


LoadModule access_compat_module modules/mod_access_compat.so
LoadModule actions_module modules/mod_actions.so
LoadModule alias_module modules/mod_alias.so
LoadModule auth_basic_module modules/mod_auth_basic.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule dir_module modules/mod_dir.so
LoadModule env_module modules/mod_env.so
LoadModule headers_module modules/mod_headers.so
LoadModule filter_module modules/mod_filter.so
LoadModule brotli_module modules/mod_brotli.so
LoadModule deflate_module modules/mod_deflate.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule mime_module modules/mod_mime.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule setenvif_module modules/mod_setenvif.so


LoadModule php_module "{{ROOT}}/bin/php-8.4.24-Win32-vs17-x64/php8apache2_4.dll"


LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
LoadModule ssl_module modules/mod_ssl.so


<IfModule php_module>
    PHPIniDir "{{ROOT}}/bin/php-8.4.24-Win32-vs17-x64"
</IfModule>


AddHandler application/x-httpd-php .php
AddType application/x-httpd-php .php


DirectoryIndex index.php index.html


BrotliCompressionQuality 5
BrotliCompressionWindow 22

AddOutputFilterByType BROTLI_COMPRESS text/html text/css application/javascript application/json image/svg+xml font/woff2 font/ttf font/otf
AddOutputFilterByType DEFLATE text/html text/css application/javascript application/json image/svg+xml


DocumentRoot "{{ROOT}}/var/www"


<Directory "{{ROOT}}/var/www">
    Options Indexes FollowSymLinks


    AllowOverride All


    Require all granted
</Directory>


Alias /phpmyadmin "{{ROOT}}/bin/phpMyAdmin-5.2.3-english"


<Directory "{{ROOT}}/bin/phpMyAdmin-5.2.3-english">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>


<VirtualHost *:80>
ServerName localhost
    DocumentRoot "{{ROOT}}/var/www"
    <Directory "{{ROOT}}/var/www">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>


Include "{{ROOT}}/var/vhosts.conf"


<IfModule mod_rewrite.c>
    RewriteEngine On
</IfModule>


PidFile "{{ROOT}}/var/logs/httpd.pid"
ErrorLog "{{ROOT}}/var/logs/apache-error.log"


LogLevel warn


CustomLog "{{ROOT}}/var/logs/access.log" combined


KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5


EnableSendfile Off
EnableMMAP Off