[mysqld]
sql_mode = "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
basedir=E:/werd/bin/mariadb-12.3.2-winx64
datadir=E:/werd/var/mariadb
port=3306
bind-address=127.0.0.1
skip-networking=0

[client]
port=3306
