// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProject(arg1:string,arg2:string):Promise<Array<main.Project>>;

export function CAInstalled():Promise<boolean>;

export function DeleteCA():Promise<boolean>;

export function GetAutostart():Promise<boolean>;

export function GetPhpPath():Promise<boolean>;

export function InstallCA():Promise<boolean>;

export function InstallMySQL():Promise<boolean>;

export function InstallSSL(arg1:string):Promise<Array<main.Project>>;

export function ListDatabases():Promise<Array<string>>;

export function ListProjects():Promise<Array<main.Project>>;

export function MySQLInstalled():Promise<boolean>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PickFolder():Promise<string>;

export function Quit():Promise<void>;

export function RemoveProject(arg1:string):Promise<Array<main.Project>>;

export function Restart(arg1:string):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<boolean>;

export function SetPhpPath(arg1:boolean):Promise<boolean>;

export function Start(arg1:string):Promise<void>;

export function StartAll():Promise<void>;

export function Stop(arg1:string):Promise<void>;

export function StopAll():Promise<void>;

export function UninstallSSL(arg1:string):Promise<Array<main.Project>>;

export function UpdateHost(arg1:string,arg2:string):Promise<Array<main.Project>>;
