// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProject(arg1:string,arg2:string):Promise<Array<main.Project>>;

export function GetPhpPath():Promise<boolean>;

export function ListProjects():Promise<Array<main.Project>>;

export function OpenURL(arg1:string):Promise<void>;

export function PickFolder():Promise<string>;

export function RemoveProject(arg1:string):Promise<Array<main.Project>>;

export function Restart(arg1:string):Promise<void>;

export function SetPhpPath(arg1:boolean):Promise<boolean>;

export function Start(arg1:string):Promise<void>;

export function StartAll():Promise<void>;

export function Stop(arg1:string):Promise<void>;

export function StopAll():Promise<void>;

export function UpdateUrl(arg1:string,arg2:string):Promise<Array<main.Project>>;
