// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1, arg2) {
  return window['go']['main']['App']['AddProject'](arg1, arg2);
}

export function GetPhpPath() {
  return window['go']['main']['App']['GetPhpPath']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function Restart(arg1) {
  return window['go']['main']['App']['Restart'](arg1);
}

export function SetPhpPath(arg1) {
  return window['go']['main']['App']['SetPhpPath'](arg1);
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function StartAll() {
  return window['go']['main']['App']['StartAll']();
}

export function Stop(arg1) {
  return window['go']['main']['App']['Stop'](arg1);
}

export function StopAll() {
  return window['go']['main']['App']['StopAll']();
}

export function UpdateUrl(arg1, arg2) {
  return window['go']['main']['App']['UpdateUrl'](arg1, arg2);
}
